### ISSUE TITLE
Cart::count()

### ISSUE THREAD

**Issue by osclancer** [bumbummen99/LaravelShoppingcart#106]
please how can I get the unique items count?
i tried to use the method `Cart::count()` but it returns by quantity, so if i have only 2 items but each one has 3 quantity it returns me 6 
but i need it to be 2 
thank you

**Comment by bumbummen99** [comment]
You can use `countInstances()` 👍 
https://github.com/bumbummen99/LaravelShoppingcart/blob/b05497d17d468035869ed6d1e5af3849c9dcbea6/src/Cart.php#L319

**Comment by osclancer** [comment]
It works, Thank you
