### ISSUE TITLE
Is there any function to re-sync the cart price just in case price of product get updated?

### ISSUE THREAD

**Issue by jamesbhatta** [bumbummen99/LaravelShoppingcart#112]
Recently I have been trying to figure out how can I reflect the current product price for the items that are in cart. Unfortunately I could not find any method like that available. 

Please let me know if there is such a functionality or else I think it would be much better if we can re-sync the product price for model implementing buyable interface.

**Comment by Sartoric** [comment]
eg. you can use Cart:update and buyable inside a foreach (Cart::content() as $cartItem)
`Cart::update($rowId, $product); // Will update the id, name and price`

or you can just update the price, as you prefer.

**Comment by sajjad606** [comment]
hi, if you are in iran you can pay any forign payments via our web site.
سایت EPAY 724 | خدمات ارزی بین الملل (https://bit.ly/3uieWwW) (سایت EPAY 724 | خدمات ارزی بین الملل (https://epay724.com))
online payments for application fees, buying gift cards, international exams fees are easier than ever ….

**Comment by rrpadilla** [comment]
@jamesbhatta see my PR #119 .
