### ISSUE TITLE
Associative model does not work?, Please provide the perfect example about it !

### ISSUE THREAD

**Issue by Keshabpal9933** [bumbummen99/LaravelShoppingcart#114]

**Comment by sajjad606** [comment]
hi, if you are in iran you can pay any forign payments via our web site.
سایت EPAY 724 | خدمات ارزی بین الملل (https://bit.ly/3uieWwW) (سایت EPAY 724 | خدمات ارزی بین الملل (https://epay724.com))
online payments for application fees, buying gift cards, international exams fees are easier than ever ….
