### ISSUE TITLE
 Store abandoned carts in the DB

### ISSUE THREAD

**Issue by xbfast** [bumbummen99/LaravelShoppingcart#116]
Hi, I'm using your code in a Laravel 5.8 application. I wanted to know how I can save the abandoned carts. Thank you and I wait for an answer. ;)

**Comment by Sartoric** [comment]
@xbfast 
You can just store all the carts in db, and delete it when the order is submitted.
So checking dates you can define if a cart is abandoned or not (via your custom code)

**Comment by sajjad606** [comment]
hi, if you are in iran you can pay any forign payments via our web site.
سایت EPAY 724 | خدمات ارزی بین الملل (https://bit.ly/3uieWwW) (سایت EPAY 724 | خدمات ارزی بین الملل (https://epay724.com))
online payments for application fees, buying gift cards, international exams fees are easier than ever ….
