### ISSUE TITLE
Limit adding to cart due to the product quantity

### ISSUE THREAD

**Issue by behzadsp** [bumbummen99/LaravelShoppingcart#122]
is there any way to limit adding products to cart due to the product quantity?
for example i have a 5 quantity of a product and i can limit it with add to cart form and user cant add 6 product to cart but when i try to add by 1 i can add it to cart as many as i want.

**Comment by bumbummen99** [comment]
You can always check the qty directly before you call `add()`. I think we could also add a method to the trait / interface to receive the remaining qty using the apps implementation rather of being included in the package itself. I am open for ideas and PRs :)
