### ISSUE TITLE
No cart instance information available on events

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [bumbummen99/LaravelShoppingcart#139]
The `CartItem` class doesn't know which cart instance it is a part of.  This is an issue when, for example, you want to wire up the automatic application of tax rates to a CartItem:

```PHP
Event::listen('cart.added', function (CartItem $cartItem) {
    if ($cartItem->model
        && $cartItem->model->taxable
        && !is_null(config('account.tax_rate'))
    ) {
        Cart::instance(???)->setTax($cartItem->rowId, config('account.tax_rate'));
    }
});
```

**Comment by bumbummen99** [comment]
Could we not add the instance to the event instead of the item? Otherwise we would have to change it if we want to add it to another isntance?

**Comment by ChrisThompsonTLDR** [comment]
Sure, but then you'd have to change all the events and listeners, right?

**Comment by ChrisThompsonTLDR** [comment]
@bumbummen99 could we get a bump on this?  We're having to maintain a fork of the repo to keep this working for us.
