### ISSUE TITLE
Upgrade to Laravel 9

### ISSUE THREAD

**Issue by alfredom78** [bumbummen99/LaravelShoppingcart#151]
Hi everyone, I try to get upgrade to Laravel 9 from Larevel 8 but I have this problem:

Problem 1
    - Root composer.json requires bumbummen99/shoppingcart ^4.1 -> satisfiable by bumbummen99/shoppingcart[4.1.0].
    - bumbummen99/shoppingcart 4.1.0 requires illuminate/support 5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||^6.0||^7.0||^8.0 -> found illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require bumbummen99/shoppingcart:*" to figure out if any version is installable, or "composer require bumbummen99/shoppingcart:^2.1" if you know which you need.

I have isntalled php version 8.1.2. 
![Screenshot_12](https://user-images.githubusercontent.com/96923931/153736268-81a78546-bac0-4bbe-a0de-046fa3c9e464.jpg)

Can you help me? Thanks.

**Comment by bumbummen99** [comment]
Yeah, this package supports up to ^8.0 and your laravel/framework is on ^9.0, that wont work and is intended 👍 The new version being compatible with L9 is currently being worked on here:
https://github.com/bumbummen99/LaravelShoppingcart/pull/145

**Comment by alfredom78** [comment]
Hello, I will be waiting for the update.
 Thank you very much for answering.


    El sábado, 12 de febrero de 2022, 08:27:46 p. m. GMT-7, Patrick ***@***.***> escribió:  
 
 


Yeah, this package supports up to ^8.0 and your laravel/framework is on ^9.0, that wont work and is intended 👍 The new version being compatible with L9 is currently being worked on here:
#145

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
