### ISSUE TITLE
Cannot install on Laravel 9 Project

### ISSUE THREAD

**Issue by mrdigitalau** [bumbummen99/LaravelShoppingcart#161]
Hello, looking at your previous issues it seemed that this project can be installed on Laravel 9.

I receive this issue when trying to install:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires bumbummen99/shoppingcart ^4.1 -> satisfiable by bumbummen99/shoppingcart[4.1.0].
    - bumbummen99/shoppingcart 4.1.0 requires illuminate/support 5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||^6.0||^7.0||^8.0 -> found illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require. 

You can also try re-running composer require with an explicit version constraint, e.g. "composer require bumbummen99/shoppingcart:*" to figure out if any version is installable, or "composer require bumbummen99/shoppingcart:^2.1" if you know which you need.

If there is anything you can suggest to be able to use 4.1 with Laravel 9 it would be greatly appreciated

**Comment by ArturCritec** [comment]
Same problem, the illuminate need be update to 9.0

**Comment by mrdigitalau** [comment]
I had to fork the latest version, go into my fork and update the requirements on the forked composer.json to:

   "require": {
        "illuminate/support": "5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||^6.0||^7.0||^8.0||^9.0",
        "illuminate/session": "5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||^6.0||^7.0||^8.0||^9.0",
        "illuminate/events": "5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||^6.0||^7.0||^8.0||^9.0",
        "nesbot/carbon": "~1.20||^1.26.3||^2.0"
    },


then add    "bumbummen99/shoppingcart": "dev-master" into "require" of my composer.json,

Then also,  add this:

 "repositories": [{
        "type": "vcs",
        "url": "https://github.com/[YOURUSERNAME]/LaravelShoppingcart.git"
    }],

It will then use your forked version of the package and it will work on Laravel 9

**Comment by kokoshneta** [comment]
The next version that’s currently being worked on does take this into account, but that seems to be some ways away still.

Since adding one extra version at the end of those four lines in `composer.json` is literally the only thing needed to get the current LaravelShoppingcart release to work on the current Laravel release, I personally think it would be a good idea to just make a point release (4.1.1?) that does that and nothing else. Then all the other changes can come in the next major release.

It seems silly to defer such a simple change to a new major version when it’s keeping the entire package from being usable on the current release of the framework it’s written for.

**Comment by designatedcoder** [comment]
Hi, I'm trying to teach a course on e-commerce and we've been using this package. You and your team have done a great job with improvements from the Crinsane version btw.  I know these things take time so I don't want to rush it.  I forked it to take a look at the code and make sure all the tests passed with the method above, but I don't want to make it public and usable when it's already been built and improved.  Is there an ETA on when it will be released? Any feedback would be greatly appreciated, thanks.

**Comment by bumbummen99** [comment]
Released an intermediate version as requested. Sorry i am currently not able to put as much time into this repository as i would like to.

**Comment by designatedcoder** [comment]
> Released an intermediate version as requested. Sorry i am currently not able to put as much time into this repository as i would like to.

No worries.... thanks for the update. It is very much appreciated.
