### ISSUE TITLE
Update the cart options

### ISSUE THREAD

**Issue by johnef** [bumbummen99/LaravelShoppingcart#17]
Hay if I try to update the price for items it updates the price, but what about options what if I need to update the options as well

I try this
`Cart::update( $row->rowId, [ 'price' => $finalProPriceCheck->price, 'flagPriceChanged' => 1 ] );`

Price updated but `option flagPriceChanged` didn't

any help here please

**Comment by bumbummen99** [comment]
It looks like the data format of your update call is incorrect. This is an example call to the method from CartTest.php which verifies that the rowId does update after changing any options.
https://github.com/bumbummen99/LaravelShoppingcart/blob/0252107aa8dcc6caab1a950231ec2eb3239e84df/tests/CartTest.php#L375

Can you try to modify the options with the following code:
```
Cart::update($row->rowId, ['options' => ['price' => $finalProPriceCheck->price, 'flagPriceChanged' => 1]]);  
```
