### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length       is 1000 bytes (SQL: alter table `shoppingcart` add primary key `shoppingcart_identifier_instance_      primary`(`identifier`, `instance`))

### ISSUE THREAD

**Issue by jordantsap** [bumbummen99/LaravelShoppingcart#170]
Composer.json:
"bumbummen99/shoppingcart": "^4.2",
"laravel/framework": "9.11",

After composer require i published migration with 
php artisan vendor:publish --provider="Gloudemans\Shoppingcart\ShoppingcartServiceProvider" --tag="migrations"
and migrate:fresh gives me this error

**Comment by bumbummen99** [comment]
https://laravel.com/docs/9.x/migrations#index-lengths-mysql-mariadb

Please don't put errors in the ticket title...
