### ISSUE TITLE
When I try to update value from options array it will remove raw.

### ISSUE THREAD

**Issue by abhishekcodercube** [bumbummen99/LaravelShoppingcart#173]
When I try to update any value from options array it will remove my raw.
eg. I have product raw with options and options have key such as "country" => 1 and "total_price" => 5 if I am going update that total_price with another number using update() method then at that time it will remove that product raw.

**Comment by abhishekcodercube** [comment]
Here is the my code for update ss: https://prnt.sc/fgLwEpx2kN8R

**Comment by bumbummen99** [comment]
Yes, as you change your options you have a diffrent position than before. A default car is not the same as a car with options color blue - you can have multiple of the same with different options. Update should return the new **row** identifier.
