### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by foRsxs** [bumbummen99/LaravelShoppingcart#176]
Users sometimes see this error, but I can't catch it. Can you check this 

A non-numeric value encountered (View: .../resources/views/sections/arrival/new.blade.php) {"view":{"view":".../vendor/bumbummen99/shoppingcart/src/Calculation/DefaultCalculator.php","data":[]},"userId":28,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): A non-numeric value encountered (View: .../resources/views/sections/arrival/new.blade.php) at .../vendor/bumbummen99/shoppingcart/src/Calculation/DefaultCalculator.php:24)

**Comment by Sartoric** [comment]
Did you check if sometimes an empty value is passed to the calculator ?
Anyway the error is self explanatory, maybe some numeric string value is passed instead of pure number

**Comment by foRsxs** [comment]
> Did you check if sometimes an empty value is passed to the calculator ?
> Anyway the error is self explanatory, maybe some numeric string value is passed instead of pure number

As I know function Add in cart check empty and is_numeric of value for quantity and price. So I can't understand why I get this error))

At this template I use only $cart->count()  and $cart->subtotalFloat() 
Maybe we have to clear all carts at 0:00 and this problem in sesssions
