### ISSUE TITLE
updating options replace all existing options

### ISSUE THREAD

**Issue by talha2k** [bumbummen99/LaravelShoppingcart#177]
Cart::update($rowId, ['options'  => ['new_option' => 'XXX']]);

using above line replaces all existing options. is there any way to add a new option to existing rowId?

**Comment by bumbummen99** [comment]
Out of the blue i would say: Get the CartItem with the rowId and then merge its existing options
```
cartItem = cart->get(rowId)
cart->update(array_merge(cartItem->options, [
    ...
]))
````

**Comment by talha2k** [comment]
Thank you! I achieved by doing following:

$cart_item = Cart::get($rowId);
$new_option = $cart_item->options->merge(['new_variable' => $new_variable_value]);
Cart::update($rowId, ['options'  => $new_option]);
