### ISSUE TITLE
Add tax per product

### ISSUE THREAD

**Issue by pixsolution** [bumbummen99/LaravelShoppingcart#180]
Hello, I want to add tax per product (because each product has different tax rates) but I can't find a way and I don't see an explanation of this case in your guide. I have tried the following way:
`
Cart::add([ 'id' => $this->product->id,
                    'name' => $this->product->title,
                    'qty' => $this->qty,
                    'price' => $this->product->price,
		    'tax' => $this->product->tax,
                    'weight' => 550,
`
and also with:
`'taxRate' => $this->product->tax,`

But nothing. How would it be done?

**Comment by diegonella** [comment]
I can see in the documentation


```
Cart::setTax($rowId, 21); $cart->setTax($rowId, 21);
```

Where $rowid Is ítem cart and 21 Is a percentage.
