### ISSUE TITLE
Incompatible with Laravel 10

### ISSUE THREAD

**Issue by tomatoTom** [bumbummen99/LaravelShoppingcart#190]
PHP 8.2, Laravel 10.0

Tried to install it via: `composer require bumbummen99/shoppingcart`

Response:
```
Problem 1
    - bumbummen99/shoppingcart dev-update_2 requires illuminate/support 5.6.*|5.7.* -> found illuminate/support[v5.6.0, ..., 5.7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[dev-refactor-database-items, dev-refactor-moneyphp, dev-refactor] require illuminate/support ^6.0|^7.0|^8.0|^9.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart 5.8.x-dev requires illuminate/support 5.1.*||5.2.*||5.3.*||5.4.*||5.5.*||5.6.*||5.7.*||5.8.* -> found illuminate/support[v5.1.1, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[1.0, ..., 1.2.1] require illuminate/support ~4 -> found illuminate/support[v4.0.0-BETA2, ..., 4.2.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart 1.3 requires illuminate/support ~5.0 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[2.0.0, ..., 2.1.2] require illuminate/support 5.1.*|5.2.* -> found illuminate/support[v5.1.1, ..., 5.2.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[2.2.0, ..., 2.2.4] require illuminate/support 5.1.*|5.2.*|5.3.* -> found illuminate/support[v5.1.1, ..., 5.3.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart 2.3.0 requires illuminate/support 5.1.*|5.2.*|5.3.*|5.4.* -> found illuminate/support[v5.1.1, ..., 5.4.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[dev-dev-laravel55, 2.4.0] require illuminate/support 5.1.*|5.2.*|5.3.*|5.4.*|5.5.* -> found illuminate/support[v5.1.1, ..., 5.5.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart 2.5.0 requires illuminate/support 5.1.*|5.2.*|5.3.*|5.4.*|5.5.*|5.6.* -> found illuminate/support[v5.1.1, ..., 5.6.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[dev-update, dev-discount, 2.6.0, ..., 2.7.7] require illuminate/support 5.1.*|5.2.*|5.3.*|5.4.*|5.5.*|5.6.*|5.7.* -> found illuminate/support[v5.1.1, ..., 5.7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[dev-back, dev-backport, 2.8.0, ..., 2.8.2] require illuminate/support 5.4.*||5.5.*||5.6.*||5.7.*||5.8.* -> found illuminate/support[v5.4.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart 2.8.3 requires illuminate/support 5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||6.0.* -> found illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., v6.0.4] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[dev-readme-cart-total-rounding-issue, dev-readme-german, dev-feature-gross-price, 2.8.4, ..., 2.8.9] require illuminate/support 5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||^6.0 -> found illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[dev-fix_cart_database_timestamps, 2.9.0, ..., 2.9.1] require illuminate/support 5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||^6.0||^7.0 -> found illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[dev-contributors-readme-action-MK_QGGzZOr, dev-contributors-readme-action-M-4_Tz-nNv, 2.10.0, 3.0.0, ..., 3.2.0, 4.0.0, ..., 4.1.0] require illuminate/support 5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||^6.0||^7.0||^8.0 -> found illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[dev-contributors-readme-action-KhPaPlWC0I, dev-contributors-readme-action-meFlvdHOi1, dev-master, 4.1.1, ..., 4.2.0] require illuminate/support 5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||^6.0||^7.0||^8.0||^9.0 -> found illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires bumbummen99/shoppingcart * -> satisfiable by bumbummen99/shoppingcart[dev-readme-cart-total-rounding-issue, ..., dev-backport, 1.0, ..., 1.3, 2.0.0, ..., 2.10.0, 3.0.0, 3.1.0, 3.2.0, 4.0.0, 4.1.0, 4.1.1, 4.2.0, 5.8.x-dev, 9999999-dev].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require bumbummen99/shoppingcart:*" to figure out if any version is installable, or "composer require bumbummen99/shoppingcart:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by neamtua** [comment]
I would also love it if this was updated for Laravel 10.

**Comment by Vincent-dejong** [comment]
Same, waiting to update to Laravel 10 until this package is compatible

**Comment by vektor-dev** [comment]
Same, I would also love it if this was updated for Laravel 10 please

**Comment by king-team-du-net** [comment]
I would also love it if this was updated for Laravel 10.

**Comment by anayarojo** [comment]
Hi, people

I found some solutions to use this package compatible with Laravel 10

### Solution 1 by @Vincent-dejong 

Using Vincent-dejong's  version:

Add his repository in your composer.json
```json
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/Vincent-dejong/laravel-shopping-cart.git",
            "no-api": true
        }
    ],
```

Select a dev version to use his compatible branch

```json
"bumbummen99/shoppingcart": "dev-update-laraval-10",
```

### Solution 2 by @phobrv 

Using phobrv's  version:

Add his repository in your composer.json
```json
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/phobrv/LaravelShoppingcart.git",
            "no-api": true
        }
    ],
```

Select a dev version to use his compatible branch

```json
"bumbummen99/shoppingcart": "dev-laravel10",
```

### Solution 3

Using my forked library
https://packagist.org/packages/anayarojo/shoppingcart

```json
"anayarojo/shoppingcart": "^4.2.1"
```

**Comment by stitpragya22** [comment]
Hi any update from official source ? for laravel 10 , just commenting  to keep this issue open

**Comment by elijahndibe** [comment]
Pls any update so far for laravel 10 from official source seriously stuck in my project

**Comment by anayarojo** [comment]
Check this comment https://github.com/bumbummen99/LaravelShoppingcart#attention

Because of that, currently, I'm using my own forked package
```
composer require anayarojo/shoppingcart
```

Some people have contributed here, you are welcome to contribute and use this forked library
https://packagist.org/packages/anayarojo/shoppingcart
https://github.com/anayarojo/laravel-shopping-cart

**Comment by elijahndibe** [comment]
> Check this comment https://github.com/bumbummen99/LaravelShoppingcart#attention
> 
> Because of that, currently, I'm using my own forked package
> 
> ```
> composer require anayarojo/shoppingcart
> ```
> 
> Some people have contributed here, you are welcome to contribute and use this forked library https://packagist.org/packages/anayarojo/shoppingcart https://github.com/anayarojo/laravel-shopping-cart

Can I also use yours

**Comment by anayarojo** [comment]
Sure @codeinvoke7, feel free to use it.

**Comment by Almoontasir** [comment]
@anayarojo Can u tell me in details
after adding the "repositories" in composer.json .... I add it after "require"{....} Then I added "bumbummen99/shoppingcart": "dev-laravel10", in require-dev{....} is it ok  Do I now need to run composire require command ...How can I publish the vendor...It showing nothing to publish

**Comment by anayarojo** [comment]
Hi @Almoontasir, there are some solutions, what do you want to do?

### Solution 1

1. In the `composer.json` of your project, put the following repository:

```json
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/anayarojo/laravel-shopping-cart.git",
            "no-api": true
        }
    ],
```

2. Update the `bumbummen99/shoppingcart` package version from any to `dev-laravel-10-support`. It'll look like this in `composer.json`:

```json
"require": {
    "bumbummen99/shoppingcart": "dev-laravel-10-support",
},
```

3. Finally, apply the changes by running  `composer install`.

### Solution 2

1. Remove the old package by running `composer remove bumbummen99/shoppingcart`

2. Install new package by running `composer require anayarojo/shoppingcart`

**Comment by Almoontasir** [comment]
Tnx bro

**Comment by mberbouch10** [comment]
I have same issue, any news bro??

**Comment by dayalsaha007** [comment]
@anayarojo 

i also use your package composer require anayarojo/shoppingcart
 on my laravel application but i have get an error. 
![Uploading Screenshot_1.png…]()

**Comment by anayarojo** [comment]
@dayalsaha007 I can't see the image, please copy the error text to your comment or re-upload the image.

**Comment by Shafique1970** [comment]
> anayarojo/shoppingcart

Showing the following error : strlen(): Argument #1 ($string) must be of type string, array given

**Comment by anayarojo** [comment]
Hi @Shafique1970, 
Please provide me the complete exception stack, to detect the line number of the error.

Moreover, please check this answer:
https://laracasts.com/discuss/channels/inertia/error-strlen-argument-1-string-must-be-of-type-string-array-given-with-anayarojoshoppingcart?page=1&replyId=907728

**Comment by Shafique1970** [comment]
Thank you Sir,

**Comment by Shafique1970** [comment]
Thank you Sir, As per your guideline the problem has been solved. But
cartCount is not showing on Cart icon. The template is as follows :
<Link :href="route('cart.index')" class="hover:text-red-700 transition">
                            <span class="bg-red-600 text-white text-xs
rounded-md p-1 absolute"
                                style="top: -10px; right: -8px;" v-if="$page
.props.cartCount > 0">{{$page.props.cartCount}}</span>
                            <icon name="cart" class="w-4 h-4 fill-current"
></icon>
                            </Link>

Regards

M.S. Islam

**Comment by anayarojo** [comment]
Hi @Shafique1970, the icon issue is not part of LaravelShoppingcart library, please check the Vue documentation:
https://vuejs.org/api/built-in-directives.html#v-if

More over, make sure Vue component props are being updated correctly.

**Comment by hellomohans** [comment]
> Check this comment https://github.com/bumbummen99/LaravelShoppingcart#attention
> 
> Because of that, currently, I'm using my own forked package
> ```
> composer require anayarojo/shoppingcart
> ```
> 
> Some people have contributed here, you are welcome to contribute and use this forked library
> https://packagist.org/packages/anayarojo/shoppingcart
> https://github.com/anayarojo/laravel-shopping-cart
> 

Bro created one demo project using laravel 10  i m beginning level,  im install your packages and publish   but.. How to use to my controller     cart::add etc etc,   how to improt that cart functions...   😭

**Comment by anayarojo** [comment]
Hi @Enterweb123, you can check a demo implementation in this repository
https://github.com/bumbummen99/LaravelShoppingcartDemo/blob/master/app/Http/Controllers/CartController.php

And example here https://github.com/bumbummen99/LaravelShoppingcart#example
