### ISSUE TITLE
not usable for laravel 10 

### ISSUE THREAD

**Issue by sirvan-monfared** [bumbummen99/LaravelShoppingcart#201]
hi,
when i want to update to laravel 10, it can not be upgraded because of this package. and here is the error:
bumbummen99/shoppingcart[1.0, ..., 1.2.1] require illuminate/support ~4 -> found illuminate/support[v4.0.0, ..., v4.2.17] but these were not loaded, likely because it conflicts with another require.

**Comment by salisu14** [comment]
The same happen to me: - bumbummen99/shoppingcart 4.2.0 requires illuminate/support 5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||^6.0||^7.0||^8.0||^9.0 -> satisfiable by illuminate/support[v5.4.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16].
    - Only one of these can be installed: illuminate/support[v5.4.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.26.2], laravel/framework[v10.0.0, ..., v10.26.2]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^10.0 -> satisfiable by laravel/framework[v10.0.0, ..., v10.26.2].
any workaround?
