### ISSUE TITLE
some problems in the downloads the package of laravel 10  this is command "composer require bumbummen99/shoppingcart"

### ISSUE THREAD

**Issue by mohammedALhakmy** [bumbummen99/LaravelShoppingcart#203]
C:\xampp\htdocs\Laravel\EcommerceC>composer require bumbummen99/shoppingcart
./composer.json has been updated
Running composer update bumbummen99/shoppingcart
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bumbummen99/shoppingcart[1.0, ..., 1.2.1] require illuminate/support ~4 -> found illuminate/support[v4.0.0, ..., v4.2.17] but these were not loaded, likely because it conflicts w
ith another require.
    - bumbummen99/shoppingcart 1.3 requires illuminate/support ~5.0 -> found illuminate/support[v5.0.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with anothe
r require.
    - bumbummen99/shoppingcart[2.0.0, ..., 2.1.2] require illuminate/support 5.1.*|5.2.* -> found illuminate/support[v5.1.1, ..., v5.2.45] but these were not loaded, likely because it
conflicts with another require.
    - bumbummen99/shoppingcart[2.2.0, ..., 2.2.4] require illuminate/support 5.1.*|5.2.*|5.3.* -> found illuminate/support[v5.1.1, ..., v5.3.23] but these were not loaded, likely becau
se it conflicts with another require.
    - bumbummen99/shoppingcart 2.3.0 requires illuminate/support 5.1.*|5.2.*|5.3.*|5.4.* -> found illuminate/support[v5.1.1, ..., v5.4.36] but these were not loaded, likely because it
conflicts with another require.
    - bumbummen99/shoppingcart 2.4.0 requires illuminate/support 5.1.*|5.2.*|5.3.*|5.4.*|5.5.* -> found illuminate/support[v5.1.1, ..., v5.5.44] but these were not loaded, likely becau
se it conflicts with another require.
    - bumbummen99/shoppingcart 2.5.0 requires illuminate/support 5.1.*|5.2.*|5.3.*|5.4.*|5.5.*|5.6.* -> found illuminate/support[v5.1.1, ..., v5.6.39] but these were not loaded, likely
 because it conflicts with another require.
    - bumbummen99/shoppingcart[2.6.0, ..., 2.7.7] require illuminate/support 5.1.*|5.2.*|5.3.*|5.4.*|5.5.*|5.6.*|5.7.* -> found illuminate/support[v5.1.1, ..., v5.7.28] but these were
not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[2.8.0, ..., 2.8.2] require illuminate/support 5.4.*||5.5.*||5.6.*||5.7.*||5.8.* -> found illuminate/support[v5.4.0, ..., v5.8.36] but these were not load
ed, likely because it conflicts with another require.
    - bumbummen99/shoppingcart 2.8.3 requires illuminate/support 5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||6.0.* -> found illuminate/support[v5.4.0, ..., v5.8.36, v6.0.0, ..., v6.0.4] but the
se were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[2.8.4, ..., 2.8.9] require illuminate/support 5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||^6.0 -> found illuminate/support[v5.4.0, ..., v5.8.36, v6.0.0, ..., v6.2
0.44] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[2.9.0, ..., 2.9.1] require illuminate/support 5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||^6.0||^7.0 -> found illuminate/support[v5.4.0, ..., v5.8.36, v6.0.0, ...
, v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[2.10.0, 3.0.0, ..., 3.2.0, 4.0.0, ..., 4.1.0] require illuminate/support 5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||^6.0||^7.0||^8.0 -> found illuminate/support[
v5.4.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - bumbummen99/shoppingcart[4.1.1, ..., 4.2.0] require illuminate/support 5.4.*||5.5.*||5.6.*||5.7.*||5.8.*||^6.0||^7.0||^8.0||^9.0 -> found illuminate/support[v5.4.0, ..., v5.8.36,
 v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires bumbummen99/shoppingcart * -> satisfiable by bumbummen99/shoppingcart[1.0, ..., 1.3, 2.0.0, ..., 2.10.0, 3.0.0, 3.1.0, 3.2.0, 4.0.0, 4.1.0, 4.1.1, 4.2
.0].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require bumbummen99/shoppingcart:*" to figure out if any version is installable, or "co
mposer require bumbummen99/shoppingcart:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by bumbummen99** [comment]
I must point you to the conversation in [this specific pull request](https://github.com/bumbummen99/LaravelShoppingcart/pull/199) and [the disclaimer in the repository's Readme](https://github.com/bumbummen99/LaravelShoppingcart/blob/master/README.md#attention). I regret to inform you that I don't have any plans to further develop this project.

This project has been deeply impacted by severe instances of copy theft and a blatant disregard for the copyleft provision within the MIT license that governs it. Basically, certain public limited companies (PLCs) have copied and commercialized this exact codebase, **profiting in the millions of euros with their product**. This unethical behavior has significantly affected my enthusiasm  and will to further develop or support this project.

While there might be other developers who continue its development, I cannot assure timely fixes or updates for this repository - I'd advise exploring alternative solutions.

**Comment by mohammedALhakmy** [comment]
Yes, indeed, I used another library, but I strongly advise you to return and develop, and even if some ideas were stolen from you, the time will come when you reach your goal, M. @bumbummen99
Owner
