### ISSUE TITLE
How to remove default tax  ??

### ISSUE THREAD

**Issue by rksumon** [bumbummen99/LaravelShoppingcart#22]
I want to get only a cart total without tax. How can I do that? please help me.

**Comment by bumbummen99** [comment]
Setting the tax rate to `0` in your config/cart.php should do the trick :+1:  If you still need taxes you can access the price by the following members on your CartItem instances:
- priceTarget (single item price)
- subtotal (single item price * qty without tax)

**Comment by rksumon** [comment]
hello sir, I can not find cart.php . where can i find it?

**Comment by rksumon** [comment]
thank you. I solve this.

**Comment by bumbummen99** [comment]
@rksumon Oops sorry, yes you first have to publish the config files of the package with artisan.
