### ISSUE TITLE
Storing extra data

### ISSUE THREAD

**Issue by mrdigitalau** [bumbummen99/LaravelShoppingcart#24]
Hey, thanks for this awesome script

I have a question... seeing that can do multiple instances, is there any way at all possible that we can store extra data pertaining to an instance in there also?

I was hoping to store some extra data relating to the cart itself, not items, but some options that are related to the cart.

For example, I am building a shopping cart for a pizza store that has multiple stores.
When they flick between stores, the cart instance changes to the one relating to that store, however, I also need to store some other data like delivery address in that instance also so it is not shared by the other instances if that makes sense?

Is there any ability to add options like this to an instance  , as opposed to doing it in the session?

Thanks very much in advance

**Comment by bumbummen99** [comment]
I think you really have to thank @Crinsane :smile: To make it short, the is currently no options like you know it from the CartItem for the Cart itself. I am going to look into it but i am currently low on time so i am open for PR's.

What you could do, depending on your situation, is to store the delivery address as its own model and assign it to the user instead of the cart if that makes sense

**Comment by mrdigitalau** [comment]
Of Course. Thank you @Crinsane for an exceptional plugin and for your hard work. It has really helped me a lot. I've actually used this script a few times and it has worked great, I then started using your fork because of its ability to work with the latest version of Laravel.

I ended up writing a wrapper class around this Cart class which helps me achieve what I needed to do :) Appreciate your response.

Cheers

**Comment by cameroncollector** [comment]
> Of Course. Thank you @Crinsane for an exceptional plugin and for your hard work. It has really helped me a lot. I've actually used this script a few times and it has worked great, I then started using your fork because of its ability to work with the latest version of Laravel.
> 
> I ended up writing a wrapper class around this Cart class which helps me achieve what I needed to do :) Appreciate your response.
> 
> Cheers

Care to share? I know it'd be really useful for me and I'm sure others in the future as well.

**Comment by mrdigitalau** [comment]
Hi @cameroncollector, basically the class didn't provide me with the ability to charge extra for options. Eg. If I had a product with 3 sizes and the sizes were all separate costs, I couldn't do it in the cart. I basically built a new class called CartClass, In options instead of 

`['size' => 'large'] `

I did

`['addon' => ['size'=>large, 'price' => 20]`

My wrapper class would have a total property would then get the total of this class using $cart->content, iterating through it, getting the prices plus the costs of the additional prices

Hope that makes sense
