### ISSUE TITLE
Translate Readme to other languages

### ISSUE THREAD

**Issue by bumbummen99** [bumbummen99/LaravelShoppingcart#25]
In order to increase the use of the Readme and to reach a broader audience. In order to participate, please create a Translation and name it e.g. "Readme_en-US.md".

**Comment by alfathony** [comment]
Hi @bumbummen99 
I wanna do this to translate in Bahasa Indonesia. As we know Indonesia had large of php and laravel developers

**Comment by jollypuppet** [comment]
Hi, I can help with the Italian translation :)

**Comment by Jam-Iko** [comment]
Hi, I would like to translate to Ukrainian or Russian. If this is okay with you, please assign this issue to me.
