### ISSUE TITLE
CartItem _construct - Wrong variable in if block

### ISSUE THREAD

**Issue by Sartoric** [bumbummen99/LaravelShoppingcart#29]
Just noticed while debugging.
The $price variable is used instead of $weight

https://github.com/bumbummen99/LaravelShoppingcart/blob/015b2a8607b90d0eeff79970fd0b958eff097682/src/CartItem.php#L101

**Comment by bumbummen99** [comment]
Very well spotted! Going to close this as the #30 has been merged.
