### ISSUE TITLE
Can't install with Laravel 6.5

### ISSUE THREAD

**Issue by yougotnet** [bumbummen99/LaravelShoppingcart#39]
Receive an error that gloudemans/shoppingcart require illuminate/events that is not compatible with Laravel 6.0.

**Comment by bumbummen99** [comment]
Hey,

this repo is a fork of the original Package by @Crisane that has been extended with still open PR's and hopefully will stay active. Did you try to install it with `gloudemans/shoppingcart`? The name of this package is `bumbummen99/shoppingcart`, you should be able to install it using the follwing command:
```
composer require bumbummen99/shoppingcart
```

**Comment by yougotnet** [comment]
I did, thanks.  It also is forked from Gloudemans and the requirements are not compatible with Laravel 6.5.

On November 7, 2019 at 2:37:14 PM, Patrick (notifications@github.com<mailto:notifications@github.com>) wrote:

Hey,

this repo is a fork of the original Package by @Crisane that has been extended with still open PR's and hopefully will stay active. Did you try to install it with gloudemans/shoppingcart? The name of this package is bumbummen99/shoppingcart, you should be able to install it using the follwing command:

composer require bumbummen99/shoppingcart

**Comment by bumbummen99** [comment]
It seems to work on my end on the latest version of Laravel. Could you please attach the output of the composer command?

**Comment by SodomousPrime** [comment]
@bumbummen99 It has installed fine for me using Laravel Framework 6.5.2

**Comment by bumbummen99** [comment]
I'll close this as i can not replicate the issue. If the issue still persists please re-open this issue 👍

**Comment by yougotnet** [comment]
I started over and install a fresh copy of laravel and it seem to install okay.

You can close the issue.
