### ISSUE TITLE
Differentiate events for merge

### ISSUE THREAD

**Issue by Sartoric** [bumbummen99/LaravelShoppingcart#40]
This is more an enhancement than an issue. 

I have listeners that listen to "add" event that do things that shouldn't be done on "merge" event, so what do you think about adding a "cart.merged' event on merge() instead of getting several "cart.added" ? 

Of course there could be an option to select between dispatching a single "merge" event or several "add" events as now

Am I the only one with this kind of need ?

**Comment by bumbummen99** [comment]
Hey, im in for it. I think it was not really tought about while implementing the method and the problematic line should be this one:
https://github.com/bumbummen99/LaravelShoppingcart/blob/18c89a495b7058d885b7ff143078ca0724c436c7/src/Cart.php#L660

We would need a way to add the cart items without raising the event. Sadly i am currently low on time so i am open and happy about any PR's 👍

**Comment by Sartoric** [comment]
I would go for the simple solution.
Adding an additional parameter/flag to "add" and "merge" to say if we want to dispatch the add events or no. Default to true.

**Comment by Sartoric** [comment]
Closing
