### ISSUE TITLE
How to attach cart to accounts?

### ISSUE THREAD

**Issue by jaesung2061** [bumbummen99/LaravelShoppingcart#44]
Hey, unfortunately I've been unable to figure out how to make the cart work only with accounts. I created the database using the [relevant documentation here](https://github.com/bumbummen99/LaravelShoppingcart#database) but I'm still not entirely sure how to implement it. Basically I want the cart only to work with the specific authenticated user and to sync with the database so they can share the cart between browsers. How can I achieve this?

**Comment by Sartoric** [comment]
> Basically I want the cart only to work with the specific authenticated user

You can set the cartid = userid so the cart is autoloaded (by you 😄 ) based on the logged in user 
Than you can use policies to manage each operation (eg. update)
Remember to manage the session as you prefer at logout

> user and to sync with the database so they can share the cart between browsers. 

You should store/update the DB cart on logout (or after every single operation done eg. add) 
and reload it (merge or restore) when the user login. 
You can achieve it using events
