### ISSUE TITLE
Help working with coupon

### ISSUE THREAD

**Issue by vanthao03596** [bumbummen99/LaravelShoppingcart#47]
I want add coupon for discount. Is there any way to do this?

**Comment by bumbummen99** [comment]
Well this package has no high level coupon code functionality but discounts. You can set a discount on your `Cart` or `CartItem` instances.

You would have to wrap that discount logic into an Coupon Code logic that checks the Coupon's limits, for example Country[,City...], Global/Product?, Timespan and so on, against the Cart instance (i.e. `$coupon->isValid($cart)`) and then apply the desired  discount on the cart or specific cart item (i.e. $coupon->applx($cart)`).

That is vaguely what i did for a project with a requirement for coupon codes.

**Comment by vanthao03596** [comment]
@bumbummen99 thanks, i will try your idea.
