### ISSUE TITLE
Fixed discounts feature

### ISSUE THREAD

**Issue by 4unkur** [bumbummen99/LaravelShoppingcart#48]
The current implementation of discounts is based on the rate (percentage). It would be nice to have the ability to set a fixed discount

**Comment by junaid-A-khan** [comment]
+1

**Comment by LonnyX** [comment]
@bumbummen99 is this in your pipeline ? Because this is causing a lot of rounding issue actually :(

**Comment by bumbummen99** [comment]
> @bumbummen99 is this in your pipeline ? Because this is causing a lot of rounding issue actually :(

I have not been actively using this package in a while thought the tests should make sure it does work correctly.
Can you please create a Unit-Test with the issue so we can reproduce it?
Also did you try to use your own calculator (For fixed discounts)?

I have been working on integrating MoneyPHP also but it is incomplete, this would fix a lot of issues while giving more adjustability.

**Comment by LonnyX** [comment]
The rounding issue I found is not a bug or something you can fix, it's Mathematically correct but sometime you don't want to have weird price (173.99 instead of 174). 
This occur because the discounts are applied with percentage per items in the cart.

What is really missing is a global fixed discount amount (not percentage).

Another thing, I noticed that discounts are already applied on the **subtotal**, that means **subtotal** and **total** are equals. Is this the expected behavior?

**Comment by bumbummen99** [comment]
> The rounding issue I found is not a bug or something you can fix, it's Mathematically correct but sometime you don't want to have weird price (173.99 instead of 174).
> This occur because the discounts are applied with percentage per items in the cart.
> 
> What is really missing is a global fixed discount amount (not percentage).
> 
> Another thing, I noticed that discounts are already applied on the **subtotal**, that means **subtotal** and **total** are equals. Is this the expected behavior?

Looking at the default Calculator subtotal should not equal total. It was setup like the following (german only) https://de.wikipedia.org/wiki/Handelskalkulation . As long as the tests work it should be desired and working.
That said you should be able to simply create your own calculator and reference it in the config, that way you could also use fixed discounts.

I already did implement it but as said it is coupled with my MoneyPHP intergration wich breaks a lot and i currently have not as much time to look into it. But if you are in for a PR i am ready to reveiw :+1:

**Comment by bumbummen99** [comment]
This will be a feature of the next major release #145

**Comment by blkaleeb** [comment]
Hi, based on this i assume @bumbummen99 already add the fixed discount feature?

how can i use the fixed global discount feature? can't find any docs to use it
