### ISSUE TITLE
Cart::update() changes the rowId

### ISSUE THREAD

**Issue by johnef** [bumbummen99/LaravelShoppingcart#49]
Now am storing the shopping cart items to database as soon as the customer add the item to cart.
I use to add the `rowId` of this item to my table.
Now whenever I do `Cart::update()` it changes the `rowId` of the item in the current session, and of course the item in the `shopping_carts` table stay with the same old `rowId`.

my question how to get the new `rowId` as soon as I fire `Cart::update()` so I can update in my table with the new one.

since I try to debug the returned `rowId` after update but it return the old one, and when the page is fully loaded it return the new `rowId`

any help here please
thanks

**Comment by Sartoric** [comment]
Found this by chance because I stumbled in an issue with priceTax calculation

(last 2 posts)
https://github.com/Crinsane/LaravelShoppingcart/issues/433 

https://github.com/FutureFutureTo/LaravelShoppingcart/commit/9a69a2144cb80b3f81efba8433a5dc1474c2f7bb

maybe the update can be integrated

**Comment by johnef** [comment]
@Sartoric Thanks I reviewed this before but clearly I'd like to know

How to get the new `rowId` as soon as I fire `Cart::update()` so I can update in my `table` with the new one.

since I try to debug the returned `rowId` after update but it return the old one, and when the page is fully loaded it return the new `rowId`
