### ISSUE TITLE
Weight option 

### ISSUE THREAD

**Issue by foRsxs** [bumbummen99/LaravelShoppingcart#50]
Hi, I try to update laravel from 5.1 to 6.8 and update shopping cart
So now i have problem "Undefined index: weight"
We don't use the weight option, how can i remove this require?

**Comment by bumbummen99** [comment]
Hey, this has already been sorted out over here https://github.com/bumbummen99/LaravelShoppingcart/issues/20
You can simply supply the default parameter or 0.

**Comment by foRsxs** [comment]
yes, simple) thanks
