### ISSUE TITLE
Only 2 items in cart

### ISSUE THREAD

**Issue by foRsxs** [bumbummen99/LaravelShoppingcart#51]
Hey) Why in cart only 2 items maximum?
When i adding 3d item on product page it's ok i see 3 items, but when i go to the cart page or just update page the last item get lost.

I can't understand whats happened coz after i use only Cart::count() and subtotal to get new information.

**Comment by foRsxs** [comment]
I found same problem in Crinsane repo https://github.com/Crinsane/LaravelShoppingcart/issues/540
but this problem not resolved

**Comment by datomnurdin** [comment]
any solution for this?

**Comment by foRsxs** [comment]
> any solution for this?

Solution is Change in .env  SESSION_DRIVER from **cookie to file** and after php artisan config:cache
