### ISSUE TITLE
how to config Cart::total() without VAT

### ISSUE THREAD

**Issue by amasahara** [bumbummen99/LaravelShoppingcart#52]
i try to get Cart::total() but it always add VAT in total and how to disable VAT in Cart::total()

**Comment by bumbummen99** [comment]
Cart tax functionality is documented in the [Readme](https://github.com/bumbummen99/LaravelShoppingcart#cartsettaxrowid-taxrate). You have multiple options at hand here, you can set the tax per CartItem (manually), set it per Cart (manually) or simply disable it globally for all new Cart instances by publishing and [changing this line](https://github.com/bumbummen99/LaravelShoppingcart/blob/677bc1c2772d3743360bd4c618a16784510796d7/src/Config/cart.php#L15) to `0` in the cart config.

If you still want to use the tax feature you can also just display the total without the tax by using the `subtotal()` method of the Cart instance.

**Comment by amasahara** [comment]
thanks for that infomation
