### ISSUE TITLE
CartItem priceTax is not correctly calculated

### ISSUE THREAD

**Issue by Sartoric** [bumbummen99/LaravelShoppingcart#55]
Probably is something inherited from the Crinsane version, but the 2 functions updateFromBuyable and updateFromArray calculate the priceTax as 
`        $this->priceTax = $this->price + $this->tax;
`

while the __get function use (as it should be) the discounted one
` $this->priceTarget + $this->tax;` 

Requesting the priceTax from the code never go through the __get()  function as the 2 methods (updateFromBuyable, updateFromArray) already added a dynamic property to the object

If there are no objections I'm going to remove the row
`        $this->priceTax = $this->price + $this->tax;
`
from both, so the method (and the "discounted" one) will be used

**Comment by bumbummen99** [comment]
Good one, just scratched my head for a moment where the `priceTax` member is :smile:  
This should be easily fixed by, as you suggested, removing both occurrences of `$this->priceTax` but i am also curious about if there should be a test verifying that this issue does not exist.

**Comment by Sartoric** [comment]
> but i am also curious about if there should be a test verifying that this issue does not exist.

In fact there are some test that check the **priceTax** value, but none of them test the value after running a Cart::update using an array or a buyable parameter. 
eg. `$cart->update('027c91341fd5cf4d2579b49c4b6a90da', ['price'=>10.00]);
`
That's when the property is added to the object

This is probably a very rare ( lucky me 🙄 👿  ) case, as I need to refresh prices before placing the order since the cart can be stored for days and prices can change every night.

**Comment by Sartoric** [comment]
PR merged
