### ISSUE TITLE
adding same product with diffrent Sizes

### ISSUE THREAD

**Issue by dheerajkukreja** [bumbummen99/LaravelShoppingcart#6]
Hi i am trying to add Same product with diffrent sizes...but it overrides the size...and one thing more
Why it is necessary to add weight index.
Cart::add(['id' => $productId, 'name' => 'Product 1', 'qty' => 1, 'price' => 9.99, 'weight' => 550, 'options' => ['size' =>  $size_option]]);

**Comment by bumbummen99** [comment]
I have added weight as a parameter as id needed the functionality for my project, also there was already an PR on the original repo. It could also be done within the options for sure. If you do not need it you can simply set it to 0 as it will not interfere with other calculations.

As far as i have tested i could not reproduce the bug you have mentioned. Could you provide a code example how you add them? Generally the rowid of the product is generated from id + options. If you add the same id with different options it will generate a new positon as the row id will differ.

**Comment by dheerajkukreja** [comment]
Thanks for the reply...
Actually i was printing the cart content just after adding the products to
cart using ajax...and it was printing the current product data only which i
added...but when i created a new function and printed cart content...it
prints the data correctly. Difftent row_id with diffrent options and same
product id...which worked for me.

**Comment by bumbummen99** [comment]
Glad to hear it is working for you too 👍 If you are experiencing any additional issues feel free to reopen or create a new issue.
