### ISSUE TITLE
502 Bad Gateway whenever Cart has more than 1 item?

### ISSUE THREAD

**Issue by frequentredundancy** [bumbummen99/LaravelShoppingcart#64]
If I submit a post request to an endpoint, and inside the controller I do something like this;
```php
        Cart::add([
            [
                'id' => '293ad', 'name' => 'Product 1', 'qty' => 1,
                'price' => 10.00, 'weight' => 550
            ],
            [
                'id' => '4832k', 'name' => 'Product 2', 'qty' => 1,
                'price' => 10.00, 'weight' => 550,
                'options' => ['size' => 'large']
            ]
        ]);
```

Whenever I return a response (even if it's just something plaintext), I get a 502 Bad Gateway. If I use `dd()` before the response that comes back fine and upon inspecting the Cart everything appears normal.

If I make the cart only 1 item like so;
```php
        Cart::add([
            [
                'id' => '293ad', 'name' => 'Product 1', 'qty' => 1,
                'price' => 10.00, 'weight' => 550
            ],
        ]);
```

It works and the response comes back just fine.

I have absolutely no idea why this is happening and can't really seem to figure it out. Hopefully someone can provide some answers!

**Comment by bumbummen99** [comment]
I suspect that there is something wrong with your integration of the package (if the issue only appears in relation to the package). So far your code looks good. I would suggest looking into your `error.log` or `laravel.log`, if that does not reveal further information then you should check with XDebug.

**Comment by frequentredundancy** [comment]
@bumbummen99 
Thanks for the quick reply.

I've checked my `laravel.log` file after clearing it and testing the issue again, and there is no log at all of any error, not even a single line of output!

I've not really had any experience with XDebug, so do you think you could give some pointers on how I could go about figuring out this issue? Not really sure the best way to approach it since I'm not even sure where to start looking. 🤣

**Comment by Sartoric** [comment]
502 Bad Gateway is commonly related to some server timeout misconfiguration, maybe you can check it 
eg. apache timeout is bigger than nginx one

**Comment by bumbummen99** [comment]
@frequentredundancy No problem :) XDebug is kinda inconvenient in it's configuration, especially if you have some special networking conditions going on, but it **really** pays off. I have ditched windows for development long ago in favor of Ubuntu so i am not really familiar with WLS and how it is working. I'd check if you can actually reach your IDE's host from you php and vica verca. Also please take a look at the [configuration documentation](https://xdebug.org/docs/remote) as there are imporant configs like the `idekey` or `remote_autostart`. Also maybe setting `remote_host` could help if you know the host, `remote_connect_back` if it is unknown.

**Comment by frequentredundancy** [comment]
@bumbummen99 Still not able to get it to work. I've tried following every guide I can possibly find and it simply refuses to work, so I don't think I'm going to be able to do any debugging.

However, after trying another package (https://github.com/darryldecode/laravelshoppingcart) I'm having exactly the same issue, and that one by default uses session storage rather than database, so I'm starting to think maybe there is some issue with my nginx config capping some type of session size or something like that. Any ideas? Since if this issue is happening on multiple packages, the only thing that is consistent between them is that I'm using Ubuntu WSL and I'm using Nginx lol.
