### ISSUE TITLE
Cart::instance('default')->destroy() cleans cart when using form but not directly in controller

### ISSUE THREAD

**Issue by jordantsap** [bumbummen99/LaravelShoppingcart#69]
I use "bumbummen99/shoppingcart": "^2.8", with "laravel/framework": "5.8.*".
The problem is exactly what the title say
I have a form in my header like below:
--------------------------
`<li class="list-group-item">
                    <form action="{{ route('cart.clean')}}" method="post">
                      {{ csrf_field() }}
                      <button title="{{__('cart.cleantitle')}}" type="submit" class="btn btn-danger" value="Remove">{{__('cart.clean')}}</button>
                    </form>
                  </li>
`---------------------------------------------``
which works as intended and delete cart products per will.
-------------------
The cart.clean function is:
---------------------------
`public function clean()
    {
      Cart::instance('default')->destroy();
      $notification = array(
        'message' => __('alerts.cartclean'),
        'alert-type' => 'success'
      );
      return redirect()->back()->with($notification);
    }`
-------------------
but in my checkoutcontroller i use:
`Cart::instance('default')->destroy();
`
or `Cart::destroy();` , i have tryed both
------------------------------
in order to clean the cart products after the order is submitted and sends the order email to the customer

Can someone help me with this??

**Comment by Sartoric** [comment]
I do exactly the same in the controller but I've never had issue 

`
Cart::destroy();Cart::erase($cartId);
`

There should be something wrong/strange in controller as you say that is working correctly while called from the form.

**Comment by jordantsap** [comment]
It's a website that i developed a long time ago, imagine it uses laravel 5.8.
What laravel and shoppingcart version do you use??
