### ISSUE TITLE
Cart item total rounding issue

### ISSUE THREAD

**Issue by pascallieverse** [bumbummen99/LaravelShoppingcart#72]
When the gross price is set to true the subtotal of each cart item gets calculated like:

``` round($this->price / (1 + ($this->taxRate / 100)), $decimals) * $this->qty ```

This results in a incorrect rounding issue:

![d0e8087272e0f6636ac411a4af8efe0e](https://user-images.githubusercontent.com/10560507/76515238-8eddf800-6459-11ea-9a94-280b1b476243.png)

The expected result of the total should be 4.00

**Comment by bumbummen99** [comment]
Sorry i am a bit sick currently so i do not have a lot of time. Could you please open a PR with a test for this case?
