### ISSUE TITLE
more than two product not adding to cart

### ISSUE THREAD

**Issue by shakhawatfci** [bumbummen99/LaravelShoppingcart#73]
when i am trying to add to cart first two product added but not adding more then two product i am using it on laravel 7 
here is my controller code 

      try{

        $id           = $request->id;
        $product_name = $request->product_name;
        $qty          = $request->qty;
        $price        = $request->price;
        $current_qty  = $request->current_qty;
        $image        = $request->product_image;
        $qty_unit     = $request->qty_unit;

        if ($qty_unit != '') 
        {
           $product_name = $product_name.'('.$qty_unit.')'; 
        }

        // checking stock 
        if($qty > $current_qty)
        {
            return response()->json(['status'=>'error','message' => 'Product out of Stock']);

        }
         $cart =  Cart::content()->where('id',$id)->first();
         // checking if cart have the product alredy 
         if($cart)
         {  

            if($cart->qty+$qty > $current_qty)
            {
            return response()->json(['status'=>'error','message' => 'Product out of Stock']);
            }

         }

         Cart::add(['id' => $id, 'name' => $product_name, 'qty' => $qty, 'price' => $price, 'weight' => 0, 'options' => ['image' => $image],'discount' => 0]);
         
         return response()->json(['status' => 'success','message' => 'Product Added To Cart']);
     }
     catch(\Exception $e)
     {
      
      return $e;

     }

**Comment by bumbummen99** [comment]
It seems that you use the package with an API client (JSON responses). **Please note that this package does use/require session to be available (web routes)**. Also it is good practice to store the cart on modifications.
Related: https://github.com/bumbummen99/LaravelShoppingcart/issues/16

**Comment by shakhawatfci** [comment]
but in my co developers pc it's working although we are having same version of php on xampp ... please suggest me what can i do instead of json response i am using it with vue js .

**Comment by shakhawatfci** [comment]
should i just return 'success' or 'error' string instant  of response json?

**Comment by bumbummen99** [comment]
If you are using api routes then i really do not know how it is working but as i said it is **not supported using api-routes** since it uses the session:
https://github.com/bumbummen99/LaravelShoppingcart/blob/86d25d9fb8f7aa062d1e444b1b4eea7e751c30e2/src/Cart.php#L63

Thought it could work if you always store the cart on modification and (re)-instanciate on the client.

**Comment by shakhawatfci** [comment]
I am nof using api route ... using it in web

**Comment by bumbummen99** [comment]
If you are using the web routes i assume there must be something wrong with the integration. How are you (re-)instanciating the cart? Also do you store the cart?

**Comment by shakhawatfci** [comment]
i didn't get your question ? store means in database storing ?

**Comment by bumbummen99** [comment]
Sorry for the late response. I meant this https://github.com/bumbummen99/LaravelShoppingcart#storing-the-cart

But after all it sounds like a session problem. What is your session driver if i may ask?
https://github.com/Crinsane/LaravelShoppingcart/issues/48#issuecomment-50444846

Also do you add unique products?

**Comment by shakhawatfci** [comment]
my session driver set to file

yes i am adding unique product to cart by id from database

**Comment by bumbummen99** [comment]
Sorry for the late response again. Could you please take a look at the [demo project](https://github.com/bumbummen99/LaravelShoppingcartDemo) i have created and see if you can reproduce the issue there?

**Comment by shakhawatfci** [comment]
Actually i think problem is with my server there is something wrong it’s
working on some others pc
