### ISSUE TITLE
Ability to use multiple discount/coupons?

### ISSUE THREAD

**Issue by frequentredundancy** [bumbummen99/LaravelShoppingcart#75]
Currently it seems like you can only have 1 discount per product. It would be cool to have the ability to have as many as you want (given they do not make the amount <= 0), so that you could say have a 10% site-wide discount with an additional 5% coupon code or something like that?

It would also be really neat to be able to get all information based on that discount. E.G
```
- id
- discount_percentage
- discount_amount (sub-total - discount_percentage)
- description (description of the discount)
- metadata (perhaps the code)
```

There are a few other cart packages that have something like this, such as; https://github.com/darryldecode/laravelshoppingcart

You can see they have this `cartConditions` array;
```
$coupon101 = new CartCondition(array(
            'name' => 'COUPON 101',
            'type' => 'coupon',
            'value' => '-5%',
        ));

Cart::addItemCondition($productID, $coupon101);
```

Hopefully this can be added!

**Comment by diegonella** [comment]
I want to do this with the coupons, did you make any progress?
The idea is good and is applicable to any cart
