### ISSUE TITLE
Session storage is not working

### ISSUE THREAD

**Issue by chiwex** [bumbummen99/LaravelShoppingcart#76]
Item added to session does not save

Product = Product::find($id);

    $user = \auth()->id();

    $item = Cart::instance($user)->add([
        'id' => $Product->id,
        'name' => $Product->name,
        'qty' => 1,
        'price' => $Product->price,
        'weight' => 200,
        'options' => ['size' => 'large']
    ])->associate($Product);

    $items = Cart::instance($user)->content();

    dd($items);

**Comment by alexteie** [comment]
I have this issue also om laravel 7
When i add something to card in different page with cart::content() is empty

**Comment by bumbummen99** [comment]
Hey, could you please take a look and see if you can reproduce the issue on the demo project i have created? I can add products there and switch between pages without any problem.

**Comment by alexteie** [comment]
On the Demo project this is not there;)

Maybe i;m doing something wrong here's mine package controller ;)

<?php

namespace XXX\YYYY\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use XXX\YYYY\Product;
use Cart;

class CartController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $id, $amount=null)
    {
        $Product = Product::findOrFail($id);

        if(empty($amount)) {
            if(empty($request->input('amount'))) {
                $amount = '1';
            } else {
                $amount = $request->input('amount');
            }
        }

        //$CartItems = Cart::content();

        Cart::add('293ad', 'Product 1', 1, 9.99, 550);

        $c = Cart::content(); /* this is filled if i dump this */
        //dd($c);
        return redirect()->route('cart.show');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
       /* this Cartitems is empty when i call this show function in next page */
        $CartItems = Cart::content();

        //dd($CartItems);
        return view('mariola::cart', [
            'Items'  =>  $CartItems
        ]);
    }
}

**Comment by alexteie** [comment]
`namespace Skylarnet\MARIOLA\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Skylarnet\SHOP\Product;
use Cart;

class CartController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $id, $amount=null)
    {
        $Product = Product::findOrFail($id);

        if(empty($amount)) {
            if(empty($request->input('amount'))) {
                $amount = '1';
            } else {
                $amount = $request->input('amount');
            }
        }

        //$CartItems = Cart::content();

        //Cart::add('293ad', 'Product 1', 1, 9.99, 550);
        //Cart::add($Product->id, $Product->name, $amount, $Product->price, ['weight' => $Product->weight]);
        Cart::add($Product->id, $Product->name, $Product->price, $Product->weight);

        $c = Cart::content();
        //dd($c);
        return redirect()->route('cart.show');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        $CartItems = Cart::content();

        //dd($CartItems);
        return view('mariola::cart', [
            'Items'  =>  $CartItems
        ]);
    }
}
`

**Comment by alexteie** [comment]
When i move my CartController.php to the App/Http/Controllers map it works
but when i use it from my package it wont...

**Comment by alexteie** [comment]
i think there something with the namespaces that when its out off app/Http/Controllers namespace

its broke..

**Comment by alexteie** [comment]
Does someone Knows why cart::content is empty when i use it in an oen package like this

**Comment by ishipilov** [comment]
Had problem with adding to cart. Solved by changing session driver from cookie to file.

**Comment by alexteie** [comment]
i have the session driver on file, but got this issue....
