### ISSUE TITLE
vendor:publish migrations not working for me

### ISSUE THREAD

**Issue by benstinton** [bumbummen99/LaravelShoppingcart#8]
php artisan vendor:publish --provider="Gloudemans\Shoppingcart\ShoppingcartServiceProvider" --tag="migrations"

didn't work

    php artisan vendor:publish --provider="Gloudemans\Shoppingcart\ShoppingcartServiceProvider"

did. 
Is it due to missing groups in 2nd publishes() method in ShoppingcartServiceProvider?

Thanks for the bundle

**Comment by InitalDevil** [comment]
1. open file on vendor/bumbummen99/shoppingcart/src/ShoppingcartServiceProvider.php
2. Edit this line
`$this->publishes([
            realpath(__DIR__.'/Database/migrations') => $this->app->databasePath().'/migrations',
        ]);`
to
`$this->publishes([
            realpath(__DIR__.'/Database/migrations') => $this->app->databasePath().'/migrations',
        ], 'migrations');`

**Comment by bumbummen99** [comment]
Thanks for pointing it out, here is the doc if someone is interested: https://laravel.com/docs/5.8/packages#publishing-file-groups

Going to update it.
