### ISSUE TITLE
Updating the cart is not quick

### ISSUE THREAD

**Issue by FIRDOUS-BHAT** [bumbummen99/LaravelShoppingcart#85]
I had developed e-com websites over core php where I used to save cart in the db. Updating the cart there works quite fine but here the cart update lags.

**Comment by bumbummen99** [comment]
Well we are always open for PR 😄 The current implementation has to always retrieve and store the cart so there is definitely some uneccessary latency overhead, but there is work being done on changing this over [here](https://github.com/bumbummen99/LaravelShoppingcart/pull/82).
