### ISSUE TITLE
tax is showing zero always

### ISSUE THREAD

**Issue by shamvilhossain** [bumbummen99/LaravelShoppingcart#88]
I am using bumbummen99 version 2.9.1 in laravel 6. when I add a product to cart, it is working well but
everytime Cart::content() is showing tax: 0. 
I did not change any settings or in cart.php in config. But still tax is showing zero.
How can i solve this??

**Comment by mtariq786** [comment]
Have you published config.php?
If so pls try to **clear config** and try again!

**Comment by shamvilhossain** [comment]
Initially it was showing zero tax. But now Its fine.

Thanks
