### ISSUE TITLE
Cart Update issue

### ISSUE THREAD

**Issue by mtariq786** [bumbummen99/LaravelShoppingcart#89]
I have updated cart with ajax request, after updating when I checked in controller it was working but when I tried to Cart::total() in ajax success response it's always showing old record unless I refresh page!!

**Comment by bumbummen99** [comment]
Id try to use xDebug and check the Cart::total after adding a product. can you try to run the unit tests and see if they pas?

Also is this related to #90?

**Comment by mtariq786** [comment]
If we return value from the controller that may could work but why should I have to return either Cart::count() or Cart::total(),  I am simply trying to get the latest cart data after updating it with ajax.

**Comment by mtariq786** [comment]
> Id try to use xDebug and check the Cart::total after adding a product. can you try to run the unit tests and see if they pass?
> 
> Also is this related to #90?

Could you pls elaborate how can I use XDebug and run unit tests specific to this detect this issue?

**Comment by bumbummen99** [comment]
Sorry for the late response.

XDebug is a PHP extension that does allow you to debug your code in your IDE during runtime. That way you can set breakpoints to pause execution and see all variables and the current state, even stepping trought your code call by call. It requires some fiddeling tought it is not as hard and defintely pays off.

The tests can be run by running `composer install && vendor/bin/phpunit` in the package directory tought they should pass.

Maybe also this does help https://github.com/bumbummen99/LaravelShoppingcartDemo. I just added a product by an ajax call there and it did return the correct total.
