### ISSUE TITLE
How to return the cart:count when using ajax

### ISSUE THREAD

**Issue by johnef** [bumbummen99/LaravelShoppingcart#90]
I am using Ajax to add products to cart

here is my Ajax code
~~~
<script>
jQuery(document).ready(function () {
    jQuery('#addToCart{{$product->id}}').click(function (e) {
        e.preventDefault();
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        let package_id = document.querySelector('input[name="package"]:checked').value;
        let pro_id ={{$product->id}};
        let quantity = jQuery('#quantity{{ $product->id }}').val();
        jQuery.ajax({
            url: "{{ route('add.to.cart') }}",
            method: 'post',
            data: {
                _token: $('meta[name="_token"]').attr('content'),
                package: package_id,
                pro_id: pro_id,
                quantity: quantity,
            },
            success: function (data) {
                console.log({{ Cart::count() }})
            },
            error: function (xhr, status, error) {
                console.log(xhr, status, error)
            },
        })
    })
})
</script>
~~~

I need to update the `Cart::count()` it always returns 0

**Comment by bumbummen99** [comment]
You are hardcoding `Cart::count()` into your console.log call there:
```js
console.log({{ Cart::count() }})
```
you could return a JSON response in your controller containing the data necessary to update your view. 
```php
return response()->json([
    'count' => Cart::count(),
]);
```
```js
console.log(data.count);
```
Else i would suggest reloading the page in your success or using a form and redirect.

**Comment by mtariq786** [comment]
If we reload the page, then I don't think we are achieving what we need to achieve through ajax.

**Comment by bumbummen99** [comment]
> If we reload the page, then I don't think we are achieving what we need to achieve through ajax.

Yes but that is the setup you have put as an example, you are hard-coding the result of `Cart::count()` in your view. When you open your page, open the inspector and check the JS, you will notice that the result of `Cart::count()` will be hardcoded in your success callback.

Simply put you wrote `console.log({{ Cart::count() }})` in your view which will become (for example) `console.log(1)` after loading the page and therefore it will only ever show 1.

As in my last response you only have two options here to make it dynamic: reloading the page and therefore updating the view (with the hardcoded value) or returning the result of `Cart::count()` in your `add.to.cart` route and use it as shown in my response:

> You are hardcoding `Cart::count()` into your console.log call there:
> 
> ```js
> console.log({{ Cart::count() }})
> ```
> 
> you could return a JSON response in your controller containing the data necessary to update your view.
> 
> ```
> return response()->json([
>     'count' => Cart::count(),
> ]);
> ```
> 
> ```js
> console.log(data.count);
> ```
> 
> Else i would suggest reloading the page in your success or using a form and redirect.
