### ISSUE TITLE
Shipping Cost in Cart

### ISSUE THREAD

**Issue by mtariq786** [bumbummen99/LaravelShoppingcart#91]
Is there any way to include shipping or any other cost which will be added in total eventually? thanks

**Comment by bumbummen99** [comment]
Currently that is not part of the package. The only thing in that regard is the weight option we provide to see the total weight of the items in the cart. Shipping can vary from situation to situation:
Sometimes you want to assign parcel types to products 1:1, another times you want to use as less parcels as possible (multiple items in one parcel) and then taxation gets interesting (here in germany).

What i ended up doing for a customer project is to write the details needed to compute shipping cost and parcel fit information in the model / cart items options and then iterate them in the checkout process computing the shipping cost manually.

**Comment by mtariq786** [comment]
yes you are right everyone could have his own shipiing cost calculator or method, my point was can we someshow add that shipping cost which we have calculated in cart like, our 
**subtotal13:100**
**tax:$13
total:$113**
Let say I want to add an additional parameter in cart which we could name any like we do in the cart instance right, so what that should have to do is simply have to add my shipping or whatever I name to the cart and I can access like **Cart::shipping()** set price through the cart that's what I am thinking!!
In nutshell, our manully added price which could be any calculated on our method we must can access through **cart::totoal()** and also our set price instance or whatever we would like to name it we can have it!!
Hope, I have cleared my point if there is anytime I can further explain!!
