### ISSUE TITLE
[Question] Update cart when products price update

### ISSUE THREAD

**Issue by vanthao03596** [bumbummen99/LaravelShoppingcart#92]
I have a problem when using package. 
-Customer add product to cart which price 10$
-Admin change price to 15$ or flash sale price -30%
-When checkout price still 10$ -> wrong.

How i can fix that ? Thanks.

**Comment by mtariq786** [comment]
are you updating cart with Ajax?

**Comment by vanthao03596** [comment]
@mtariq786 ajax not matter here.

**Comment by bumbummen99** [comment]
The package does not yet update the CartItem price on deserializing, tought we are always open for PR 👍.
Meanwhile you could listen for the cart restored event or after restoring your cart and loop trought the cart content updating the price.

```php
foreach ($cart->content() as $cartItem) {
    $cartItem->price = $cartItem->model->price;
}
```

**Comment by vanthao03596** [comment]
@bumbummen99 when call $cartItem->model it hit database query each time on Crinsane/LaravelShoppingcart. Is our package fix this problem ?

**Comment by mtariq786** [comment]
@vanthao03596 let say when a customer added a product to cart it will take price at that time, but after while if admin or someone update the price, how will our package know, obviously for that as @bumbummen99 said, we have to communicate with database if it was stored there! but even if we have to update cart price our cart must have to communicate with database and have to update all products prices before going to checkout!

**Comment by bumbummen99** [comment]
@mtariq786 Yep. In order to get the updated price you will have to get it from the actual source which would be your database. 

Just an idea you could use Laravels [caching](https://laravel.com/docs/7.x/cache) to drastically reduce Database queries, this would also require that you [invalidate the cache](https://laravel.com/docs/7.x/cache#removing-items-from-the-cache) on updating your Model / price. Could be as simple as:

```php
foreach ($cart->content() as $cartItem) {
    $cartItem->price = \Cache::rememberForever($cartItem->modelFQCN.'-price', function () use ($cartItem) {
        return $cartItem->model->price;
    });
}


...


/* For example in your model */
\Cache::forget(get_class($this).'-price');
```
